[Common]
Enable 			= 1

NPC 			= 606



DisplayCommands		= 1

WaitingMap 		= 85
WaitingX 		= 70
WaitingY		= 47

BluTeamX		= 38
BluTeamY		= 39

RedTeamX		= 91
RedTeamY		= 76

WaitingTime		= 1


EventTime		= 5

RewardItem		= 1
ItemRewardType	= 14
ItemRewardIndex	= 11
ItemRewardLevel	= 12
RewardItemCount = 1


RewardCredit		= 20
RewardWCoin		= 11

;~~~~~~~~~~~~~~~~
;	    TIME
;	Hour	| Minute
;~~~~~~~~~~~~~~~~
1
	19	12
end