//==================================================================================================================
// Castle Siege
//==================================================================================================================
[GameServerInfo]
CastleSiegeRun		= 1
CastleCycleStartYear	=0
CastleCycleStartMonth	=0
CastleCycleStartDay	=0
MarkOfTheLord		= 100;	; mark of the lord drop rate - N/10000
;-------------------------------------------------------------------------------
; castle siege state explanation (run as sequence)
;
; 1 - register castle siege state
; 2 - idle state
; 3 - register mark of the lord state
; 4 - idle state
; 5 - castle attack guild notification state
; 6 - ready for castle siege state
; 7 - castle siege start state
; 8 - castle siege end state
; 9 - end of cycle (restart from state 1, automaticaly)
;-------------------------------------------------------------------------------
CastleSpecificState	    =0
CastleStateStartYear	=0
CastleStateStartMonth	=0
CastleStateStartDay	    =0
CastleStateStartHour	=0
CastleStateStartMinute	=0


